
name: CI

on: [ push, workflow_dispatch ]



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: warmup
        run: |
          $vsInstallRoot = (Get-VisualStudioInstance).InstallationPath
          $devEnvPath = "$vsInstallRoot\Common7\IDE\devenv.exe"   
          & "$devEnvPath" /RootSuffix Exp /ResetSettings General.vssettings /Command File.Exit
          mkdir temp
          cd temp
          & $env:ProgramFiles\dotnet\dotnet.exe new console
           & "$devEnvPath" temp.csproj /build Release | Out-Null
        shell: powershell

      - name: Run a multi-line script
        run: |
          $vsInstallRoot = (Get-VisualStudioInstance).InstallationPath
          $devEnvPath = "$vsInstallRoot\Common7\IDE\devenv.exe"   
          & "$devEnvPath" /RootSuffix Exp /ResetSettings General.vssettings /Command File.Exit
          & $env:ProgramFiles\dotnet\dotnet.exe new console
          (Measure-Command { & "$devEnvPath" warmup.vdproj /build Release | Out-Null }).TotalSeconds
          (Measure-Command { & "$devEnvPath" warmup.vdproj /build Release | Out-Null }).TotalSeconds
        shell: powershell
